<%@ Page Title="Order" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Order.aspx.cs" Inherits="TopTravel.Order" %>

<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <hgroup class="title">
        <h1><%: Title %>.</h1>
    </hgroup>


    <article>
                    
        <h1>Shopping Cart</h1>

        <asp:GridView ID="GridView1" runat="server" Width="100%" AutoGenerateColumns="False" CssClass="Grid" AlternatingRowStyle-CssClass="alt" AutoGenerateDeleteButton="true" OnRowDeleting="GridView1_RowDeleting" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
                        <columns>
                            <asp:boundfield datafield="Id" headertext="ID"/>
                            <asp:boundfield datafield="Product" headertext="Product"/>
                            <asp:boundfield datafield="ProductName" headertext="Product Name"/>
                            <asp:boundfield datafield="Adults" headertext="Adults"/>
                            <asp:boundfield datafield="Children" headertext="Children"/>
                            <asp:boundfield datafield="Price" headertext="Price/Person €"/>
                            <asp:boundfield datafield="TotalPrice" headertext="Total Price €"/> 
                            <asp:buttonfield buttontype="Button" CommandName="select" headertext="Buy product" text="Confirm and buy"/>
                        </columns>
                    <PagerStyle HorizontalAlign="Center" CssClass="GridPager" />
         </asp:GridView>
        
        

        <h1>History Cart</h1>

        <asp:GridView ID="GridView2" runat="server" Width="100%" AutoGenerateColumns="False" CssClass="Grid" AlternatingRowStyle-CssClass="alt">
                        <columns>
                            <asp:boundfield datafield="Id" headertext="ID"/>
                            <asp:boundfield datafield="Product" headertext="Product"/>
                            <asp:boundfield datafield="ProductName" headertext="Product Name"/>
                            <asp:boundfield datafield="Adults" headertext="Adults"/>
                            <asp:boundfield datafield="Children" headertext="Children"/>
                            <asp:boundfield datafield="Price" headertext="Price/Person €"/>
                            <asp:boundfield datafield="TotalPrice" headertext="Total Price €"/> 
                        </columns>
                    <PagerStyle HorizontalAlign="Center" CssClass="GridPager" />
         </asp:GridView>

    </article>

</asp:Content>