<%@ Page Title="CarRental Admin" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CarRental.aspx.cs" Inherits="TopTravel.CarRentalAdmin" %>

<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <hgroup class="title">
        <h1><%: Title %>.</h1>
        <h2>Control Panel.<br />
        </h2>
    </hgroup>
    <div>
        <div>
        <asp:RadioButtonList ID="typeAdmin" runat="server" OnSelectedIndexChanged="radioChange" AutoPostBack="True">
            <asp:ListItem Value="Hotel">Hotel</asp:ListItem>
            <asp:ListItem Value="Cruise">Cruise</asp:ListItem>
            <asp:ListItem Value="Flight">Flight</asp:ListItem>
            <asp:ListItem Value="Bus">Bus</asp:ListItem>
            <asp:ListItem Value="Train">Train</asp:ListItem>
            <asp:ListItem Value="CarRental">Car Rental</asp:ListItem>
            <asp:ListItem Value="SpaceTravel">Space Travel</asp:ListItem>
        </asp:RadioButtonList>
        <br />
            <div>
          <label>ID</label>
            <asp:TextBox id="idCr" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
          <label>City</label>
            <asp:TextBox id="cCr" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Brand</label>
            <asp:TextBox id="brandCr" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Model</label>
            <asp:TextBox id="modelCr" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Days</label>
            <asp:TextBox id="daysCr" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
            <label>Price</label>
            <asp:TextBox id="priceCr" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Company</label>
            <asp:TextBox id="companyCr" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Extras</label>
            <asp:TextBox id="extrasCr" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
            <label>Image</label>
            <asp:TextBox id="imageCr" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
          <asp:Button ID="EditButton" runat="server" Text="Edit" OnClick="GridView1_sendUpdate" CssClass="inputBottom" />
          <asp:Button ID="InsertButton" runat="server" Text="Insert" OnClick="sendInsert" CssClass="inputBottom" />
      </div>

     <asp:GridView ID="GridView1" runat="server" Width="100%" AutoGenerateColumns="False" CssClass="Grid" AlternatingRowStyle-CssClass="alt" AutoGenerateSelectButton="true" AutoGenerateDeleteButton="true" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" OnRowDeleting="GridView1_RowDeleting" >
                <columns>
                    <asp:boundfield datafield="Id" headertext="ID"/>
                    <asp:boundfield datafield="City" headertext="City"/>
                    <asp:boundfield datafield="Brand" headertext="Brand"/>
                    <asp:boundfield datafield="Model" headertext="Model"/>     
                    <asp:boundfield datafield="Days" headertext="Days"/>
                    <asp:boundfield datafield="price" headertext="Price"/>
                    <asp:boundfield datafield="company" headertext="Company"/>
                    <asp:boundfield datafield="extras" headertext="Extras"/>  
                    <asp:boundfield datafield="image" headertext="Image"/>        
                </columns>
                <PagerStyle HorizontalAlign="Center" CssClass="GridPager" />
     </asp:GridView>
        </div>
        </div>
</asp:Content>
