<%@ Page Title="Hotel Admin" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Hotel.aspx.cs" Inherits="TopTravel.HotelAdmin" %>

<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <hgroup class="title">
        <h1><%: Title %>.</h1>
        <h2>Control Panel.<br />
        </h2>
    </hgroup>

     <div>
        <asp:RadioButtonList ID="typeAdmin" runat="server" OnSelectedIndexChanged="radioChange" AutoPostBack="True">
            <asp:ListItem Value="Hotel">Hotel</asp:ListItem>
            <asp:ListItem Value="Cruise">Cruise</asp:ListItem>
            <asp:ListItem Value="Flight">Flight</asp:ListItem>
            <asp:ListItem Value="Bus">Bus</asp:ListItem>
            <asp:ListItem Value="Train">Train</asp:ListItem>
            <asp:ListItem Value="CarRental">Car Rental</asp:ListItem>
            <asp:ListItem Value="SpaceTravel">Space Travel</asp:ListItem>
        </asp:RadioButtonList>
        <br />

       <div>
          <label>ID</label>
            <asp:TextBox id="idH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
          <label>Name</label>
            <asp:TextBox id="nameH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>City</label>
            <asp:TextBox id="cityH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Phone</label>
            <asp:TextBox id="phoneH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Address</label>
            <asp:TextBox id="addressH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Email</label>
           <asp:TextBox id="emailH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Stars</label>
            <asp:TextBox id="starsH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Bedrooms</label>
            <asp:TextBox id="bedroomsH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Price</label>
            <asp:TextBox id="priceH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Company</label>
            <asp:TextBox id="companyH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Extras</label>
            <asp:TextBox id="extrasH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
          <asp:Button ID="EditButton" runat="server" Text="Edit" OnClick="GridView1_sendUpdate" CssClass="inputBottom" />
          <asp:Button ID="InsertButton" runat="server" Text="Insert" OnClick="sendInsert" CssClass="inputBottom" />
      </div>

    </div>
    <asp:GridView ID="GridView1" runat="server" Width="100%" AutoGenerateColumns="False" CssClass="Grid" AlternatingRowStyle-CssClass="alt" AutoGenerateSelectButton="true" AutoGenerateDeleteButton="true" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" OnRowDeleting="GridView1_RowDeleting" >
                <columns>
                    <asp:boundfield datafield="Id" headertext="ID"/>
                    <asp:boundfield datafield="Name" headertext="Name"/>
                    <asp:boundfield datafield="City" headertext="City"/>
                    <asp:boundfield datafield="Phone" headertext="Phone"/>
                    <asp:boundfield datafield="Adress" headertext="Adress"/>
                    <asp:boundfield datafield="Email" headertext="Email"/>
                    <asp:boundfield datafield="Stars" headertext="Stars"/>
                    <asp:boundfield datafield="Bedrooms" headertext="Bedrooms"/>
                    <asp:boundfield datafield="Price" headertext="Price"/>
                    <asp:boundfield datafield="company" headertext="Company"/>
                    <asp:boundfield datafield="extras" headertext="Extras"/>           
                </columns>
                <PagerStyle HorizontalAlign="Center" CssClass="GridPager" />
     </asp:GridView>    
</asp:Content>