<%@ Page Title="Hotel Admin" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Hotel.aspx.cs" Inherits="TopTravel.HotelAdmin" %>

<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <hgroup class="title">
        <h1><%: Title %>.</h1>
        <h2>Control Panel.<br />
        </h2>
    </hgroup>

    <style type="text/css">
      .hiddencol
      {
        display: none;
      }
    </style>

     <div>
        <asp:RadioButtonList ID="typeAdmin" runat="server" OnSelectedIndexChanged="radioChange" AutoPostBack="True" RepeatDirection="Horizontal" CssClass="radioButtonList">
            <asp:ListItem Value="Hotel">Hotel</asp:ListItem>
            <asp:ListItem Value="Cruise">Cruise</asp:ListItem>
            <asp:ListItem Value="Flight">Flight</asp:ListItem>
            <asp:ListItem Value="Bus">Bus</asp:ListItem>
            <asp:ListItem Value="Train">Train</asp:ListItem>
            <asp:ListItem Value="CarRental">Car Rental</asp:ListItem>
            <asp:ListItem Value="SpaceTravel">Space Travel</asp:ListItem>
        </asp:RadioButtonList>
        <br />
        <asp:GridView ID="GridView1" runat="server" Width="100%" AutoGenerateColumns="False" CssClass="Grid" AlternatingRowStyle-CssClass="alt" AutoGenerateSelectButton="true" AutoGenerateDeleteButton="true" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" OnRowDeleting="GridView1_RowDeleting" >
                <columns>
                    <asp:boundfield datafield="Id" headertext="ID"/>
                    <asp:boundfield datafield="Name" headertext="Name"/>
                    <asp:boundfield datafield="City" headertext="City"/>
                    <asp:boundfield datafield="Phone" headertext="Phone"/>
                    <asp:boundfield datafield="Adress" headertext="Adress"/>
                    <asp:boundfield datafield="Email" headertext="Email"/>
                    <asp:boundfield datafield="Stars" headertext="Stars"/>
                    <asp:boundfield datafield="Bedrooms" headertext="Bedrooms"/>
                    <asp:boundfield datafield="Price" headertext="Price"/>
                    <asp:boundfield datafield="company" headertext="Company"/>
                    <asp:boundfield datafield="extras" headertext="Extras"/>  
                    <asp:boundfield datafield="image" headertext="Images" ItemStyle-CssClass="hiddencol" HeaderStyle-CssClass="hiddencol"/>          
                </columns>
                <PagerStyle HorizontalAlign="Center" CssClass="GridPager" />
     </asp:GridView>
         <br />
       <div>
          <label>ID</label>
            <asp:TextBox id="idH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
          <label>Name</label>
            <asp:TextBox id="nameH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>City</label>
            <asp:TextBox id="cityH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Phone</label>
            <asp:TextBox id="phoneH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Address</label>
            <asp:TextBox id="addressH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Email</label>
           <asp:TextBox id="emailH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Stars</label>
            <asp:TextBox id="starsH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Bedrooms</label>
            <asp:TextBox id="bedroomsH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Price</label>
            <asp:TextBox id="priceH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Company</label>
            <asp:TextBox id="companyH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Extras</label>
            <asp:TextBox id="extrasH" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Image</label>
            <asp:TextBox id="imageT" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
          <asp:Button ID="EditButton" runat="server" Text="Edit" OnClick="GridView1_sendUpdate" CssClass="inputBottom" validationgroup="2" />
          <asp:Button ID="InsertButton" runat="server" Text="Insert" OnClick="sendInsert" CssClass="inputBottom" validationgroup="2" />
      </div>     
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="You must specify the id." ControlToValidate="idH" validationgroup="2" forecolor="Red" CssClass="validator" Display="None"></asp:RequiredFieldValidator>
         <asp:CompareValidator ID="CompareValidator2" runat="server" Operator="DataTypeCheck" Type="Integer" ControlToValidate="idH" ErrorMessage="Id must be a number" validationgroup="2"  Display="None"/>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="You must specify the name." ControlToValidate="nameH" validationgroup="2" forecolor="Red" CssClass="validator" Display="None"></asp:RequiredFieldValidator>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ErrorMessage="You must specify the city." ControlToValidate="cityH" validationgroup="2" forecolor="Red" CssClass="validator" Display="None"></asp:RequiredFieldValidator>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ErrorMessage="You must specify the phone number." ControlToValidate="phoneH" validationgroup="2" forecolor="Red" CssClass="validator" Display="None"></asp:RequiredFieldValidator>
         <asp:CompareValidator ID="CompareValidator3" runat="server" Operator="DataTypeCheck" Type="Integer" ControlToValidate="phoneH" ErrorMessage="Phone must be a number" validationgroup="2" Display="None" />
            <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" ErrorMessage="You must specify the address." ControlToValidate="addressH" validationgroup="2" forecolor="Red" CssClass="validator" Display="None"></asp:RequiredFieldValidator>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" ErrorMessage="You must specify the email." ControlToValidate="emailH" validationgroup="2" forecolor="Red" CssClass="validator" Display="None"></asp:RequiredFieldValidator>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator7" runat="server" ErrorMessage="You must specify the numer of stars." ControlToValidate="starsH" validationgroup="2" forecolor="Red" CssClass="validator" Display="None"></asp:RequiredFieldValidator>
         <asp:CompareValidator ID="CompareValidator4" runat="server" Operator="DataTypeCheck" Type="Integer" ControlToValidate="starsH" ErrorMessage="Stars must be a number" validationgroup="2" Display="None" />
            <asp:RequiredFieldValidator ID="RequiredFieldValidator8" runat="server" ErrorMessage="You must specify the numer of bedrooms." ControlToValidate="bedroomsH" validationgroup="2" forecolor="Red" CssClass="validator" Display="None"></asp:RequiredFieldValidator>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator9" runat="server" ErrorMessage="You must specify the price." ControlToValidate="priceH" validationgroup="2" forecolor="Red" CssClass="validator" Display="None"></asp:RequiredFieldValidator>
         <asp:CompareValidator ID="CompareValidator5" runat="server" Operator="DataTypeCheck" Type="Integer" ControlToValidate="priceH" ErrorMessage="Price must be a number" validationgroup="2" Display="None" />
            <asp:RequiredFieldValidator ID="RequiredFieldValidator10" runat="server" ErrorMessage="You must specify the number of the company." ControlToValidate="companyH" validationgroup="2" forecolor="Red" CssClass="validator" Display="None"></asp:RequiredFieldValidator>
         <asp:CompareValidator ID="CompareValidator6" runat="server" Operator="DataTypeCheck" Type="Integer" ControlToValidate="companyH" ErrorMessage="Company must be a number" validationgroup="2" Display="None" />
            <asp:RequiredFieldValidator ID="RequiredFieldValidator11" runat="server" ErrorMessage="You must specify the numer of the extra." ControlToValidate="extrasH" validationgroup="2" forecolor="Red" CssClass="validator" Display="None"></asp:RequiredFieldValidator>
         <asp:CompareValidator ID="CompareValidator7" runat="server" Operator="DataTypeCheck" Type="Integer" ControlToValidate="extrasH" ErrorMessage="Extras must be a number" validationgroup="2" Display="None" />

            <asp:ValidationSummary ID="ValidationSummary3" runat="server" DisplayMode="BulletList" ShowSummary="True" validationgroup="2" forecolor="Red" ShowValidationErrors="True" />
    </div>  
</asp:Content>