<%@ Page Title="Train Admin" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Train.aspx.cs" Inherits="TopTravel.TrainAdmin" %>

<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <hgroup class="title">
        <h1><%: Title %>.</h1>
        <h2>Control Panel.<br />
        </h2>
    </hgroup>

    <style type="text/css">
      .hiddencol
      {
        display: none;
      }
    </style>
        <div>
        <asp:RadioButtonList ID="typeAdmin" runat="server" OnSelectedIndexChanged="radioChange" AutoPostBack="True" RepeatDirection="Horizontal" CssClass="radioButtonList">
            <asp:ListItem Value="Hotel">Hotel</asp:ListItem>
            <asp:ListItem Value="Cruise">Cruise</asp:ListItem>
            <asp:ListItem Value="Flight">Flight</asp:ListItem>
            <asp:ListItem Value="Bus">Bus</asp:ListItem>
            <asp:ListItem Value="Train">Train</asp:ListItem>
            <asp:ListItem Value="CarRental">Car Rental</asp:ListItem>
            <asp:ListItem Value="SpaceTravel">Space Travel</asp:ListItem>
        </asp:RadioButtonList>
        <br />
         <asp:GridView ID="GridView1" runat="server" Width="100%" AutoGenerateColumns="False" CssClass="Grid" AlternatingRowStyle-CssClass="alt" AutoGenerateSelectButton="true" AutoGenerateDeleteButton="true" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" OnRowDeleting="GridView1_RowDeleting" >
                <columns>
                    <asp:boundfield datafield="Id" headertext="Departure ID"/>
                    <asp:boundfield datafield="departureTime" headertext="Departure Time"/>
                    <asp:boundfield datafield="arrivalTime" headertext="Arrival Time"/>
                    <asp:boundfield datafield="departureCity" headertext="Departure"/>     
                    <asp:boundfield datafield="destinationCity" headertext="Destination"/>
                    <asp:boundfield datafield="price" headertext="Price"/>
                    <asp:boundfield datafield="company" headertext="Company"/>
                    <asp:boundfield datafield="extras" headertext="Extras"/>  
                    <asp:boundfield datafield="images" headertext="Images" ItemStyle-CssClass="hiddencol" HeaderStyle-CssClass="hiddencol"/>        
                </columns>
                <PagerStyle HorizontalAlign="Center" CssClass="GridPager" />
         </asp:GridView>
        <br />
            <div>
          <label>ID</label>
            <asp:TextBox id="idT" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
          <label>Departure Time</label>
            <asp:TextBox id="depTimeT" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Arrival Time</label>
            <asp:TextBox id="arTimeT" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Departure City</label>
            <asp:TextBox id="depCiT" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Destination City</label>
            <asp:TextBox id="destinationT" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
            <label>Price</label>
            <asp:TextBox id="priceT" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Company</label>
            <asp:TextBox id="companyT" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
           <label>Extras</label>
            <asp:TextBox id="extrasT" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
            <label>Image</label>
            <asp:TextBox id="imageT" TextMode="SingleLine" Columns="30" runat="server" CssClass="input" />
          <asp:Button ID="EditButton" runat="server" Text="Edit" OnClick="GridView1_sendUpdate" CssClass="inputBottom" />
          <asp:Button ID="InsertButton" runat="server" Text="Insert" OnClick="sendInsert" CssClass="inputBottom" />
      </div>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="You must specify the id." ControlToValidate="idt" forecolor="Red" CssClass="validator"></asp:RequiredFieldValidator>
         <asp:CompareValidator ID="CompareValidator2" runat="server" Operator="DataTypeCheck" Type="Integer" ControlToValidate="idt" ErrorMessage="Id must be a number"  />
            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="You must specify the departure time." ControlToValidate="depTimet" forecolor="Red" CssClass="validator" ></asp:RequiredFieldValidator>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ErrorMessage="You must specify the arrival time." ControlToValidate="arTimet"  forecolor="Red" CssClass="validator" ></asp:RequiredFieldValidator>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" ErrorMessage="You must specify the destination city." ControlToValidate="destinationT"  forecolor="Red" CssClass="validator" ></asp:RequiredFieldValidator>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" ErrorMessage="You must specify the departure city." ControlToValidate="depCiT"  forecolor="Red" CssClass="validator"></asp:RequiredFieldValidator>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator9" runat="server" ErrorMessage="You must specify the price." ControlToValidate="priceT" forecolor="Red" CssClass="validator" ></asp:RequiredFieldValidator>
         <asp:CompareValidator ID="CompareValidator5" runat="server" Operator="DataTypeCheck" Type="Integer" ControlToValidate="priceT" ErrorMessage="Price must be a number" />
            <asp:RequiredFieldValidator ID="RequiredFieldValidator10" runat="server" ErrorMessage="You must specify the number of the company." ControlToValidate="companyT"  forecolor="Red" CssClass="validator"></asp:RequiredFieldValidator>
         <asp:CompareValidator ID="CompareValidator6" runat="server" Operator="DataTypeCheck" Type="Integer" ControlToValidate="companyT" ErrorMessage="Company must be a number"  Display="None" />
            <asp:RequiredFieldValidator ID="RequiredFieldValidator11" runat="server" ErrorMessage="You must specify the numer of the extra." ControlToValidate="extrasT"  forecolor="Red" CssClass="validator" ></asp:RequiredFieldValidator>
         <asp:CompareValidator ID="CompareValidator7" runat="server" Operator="DataTypeCheck" Type="Integer" ControlToValidate="extrasT" ErrorMessage="Extras must be a number" />
        </div>
</asp:Content>